development:
  adapter: mysql2
  encoding: utf8
  database: database
  username: username
  password: password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: database
  username: username
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: database
  username: username
  password: password
  host: localhost
